# Aspectos metodológicos

## Ficha técnica

+--------------------------------+----------------------------------------------------------------------------------+
| Categoría                      | Descripción                                                                      |
+================================+==================================================================================+
| Población objetivo             | Estudiantes de recién ingreso a la Universidad de Santander en el periodo 2025-2 |
+--------------------------------+----------------------------------------------------------------------------------+
| Campus                         | Bucaramanga\                                                                     |
|                                | Cúcuta\                                                                          |
|                                | Valledupar                                                                       |
+--------------------------------+----------------------------------------------------------------------------------+
| Total estudiantes              |                                                                                  |
+--------------------------------+----------------------------------------------------------------------------------+
| Método de recolección de datos | Formulario multicampus (111 preguntas)                                           |
+--------------------------------+----------------------------------------------------------------------------------+
| Aspectos evaluados             | Sesión 1. Información personal y académica                                       |
|                                |                                                                                  |
|                                | Sesión 2. Aspectos sociodemográficos                                             |
|                                |                                                                                  |
|                                | Sesión 3. Salud integral                                                         |
|                                |                                                                                  |
|                                | Sesión 4. Fomento de la cultura                                                  |
|                                |                                                                                  |
|                                | Sesión 5. Deportes y esparcimiento                                               |
|                                |                                                                                  |
|                                | Sesión 6. Desarrollo humano                                                      |
+--------------------------------+----------------------------------------------------------------------------------+
| Enlace                         |                                                                                  |
+--------------------------------+----------------------------------------------------------------------------------+
| Periodo de aplicación          | 04 de agosto - 04 de septiembre de 2025                                          |
+--------------------------------+----------------------------------------------------------------------------------+
| Tasa de respuesta              |                                                                                  |
+--------------------------------+----------------------------------------------------------------------------------+
| Herramienta de tabulación      | Excel, RStudio, Tableau 2024.2.2                                                 |
+--------------------------------+----------------------------------------------------------------------------------+

## Tasa de respuesta

La reciente encuesta aplicada a los estudiantes de primer semestre registró un 86% de participación entre los 618 matriculados. Los programas con 100% de respuesta incluyen Antropología, Bacteriología y Laboratorio Clínico, Contaduría Pública, Licenciatura en Educación Infantil, Mercadeo y Publicidad, Microbiología Industrial, Psicología, Tecnología en Supervisión de Obras Civiles y Terapia Ocupacional.

+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Programas**                                                            | **Respuesta encuesta**   | **Matriculados primer semestre**   | **% de respuesta**   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Administración de negocios internacionales**                           | 15                       | 16                                 | 94                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Aministración financiera**                                             | 18                       | 23                                 | 78                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Antropología**                                                         | 7                        | 7                                  | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Bacteriología y laboratorio clínico**                                  | 29                       | 29                                 | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Comunicación social y periodismo**                                     | 9                        | 10                                 | 90                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Contaduría pública**                                                   | 10                       | 10                                 | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Derecho**                                                              | 13                       | 20                                 | 65                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Enfermería**                                                           | 18                       | 24                                 | 75                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Fisioterapia**                                                         | 28                       | 37                                 | 76                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Fonoaudiología**                                                       | 18                       | 19                                 | 95                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Geología**                                                             | 5                        | 9                                  | 56                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Ingeniería agroindustrial**                                            | 9                        | 11                                 | 82                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Ingeniería civil**                                                     | 15                       | 20                                 | 75                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Ingeniería de software**                                               | 56                       | 60                                 | 93                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Ingeniería en ciencias de la computación e inteligencia artificial**   | 8                        | 10                                 | 80                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Ingeniería industrial**                                                | 7                        | 9                                  | 78                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Instrumentación quirúrgica**                                           | 51                       | 52                                 | 98                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Instrumentación quirúrgica - BOG**                                     | 27                       | 28                                 | 96                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Licenciatura en educación infantil**                                   | 11                       | 11                                 | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Medicina**                                                             | 51                       | 57                                 | 89                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Medicina veterinaria**                                                 | 66                       | 73                                 | 90                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Mercadeo y publicidad**                                                | 26                       | 26                                 | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Microbiología industrial**                                             | 14                       | 14                                 | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Psicología**                                                           | 25                       | 25                                 | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Tecnología en comunicación grafica**                                   | 22                       | 24                                 | 92                   |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Tecnología supervisión de obras civiles**                              | 5                        | 5                                  | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Terapia ocupacional**                                                  | 17                       | 17                                 | 100                  |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
| **Total**                                                                | **560**                  | **646**                            | **86**               |
+--------------------------------------------------------------------------+--------------------------+------------------------------------+----------------------+
